In [1]:
import numpy as np

In [37]:
# Exercise 1: Create a 3x3 array with random values
random_array = np.random.randint(-10, 10, (3, 3))
print("Exercise 1: Random Array:\n", random_array)

Exercise 1: Random Array:
 [[ -1   4   8]
 [  3   4   2]
 [  8  -6 -10]]


In [10]:
# Exercise 2: Create a 1D array with 10 equally spaced values from 0 to 1 (inclusive)
linspace_array = np.linspace(0,1,10)
print("Exercise 2: Linspace Array:", linspace_array)

Exercise 2: Linspace Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
# Exercise 3: Reshape the linspace_array into a 5x2 matrix
reshaped_linspace = np.reshape(linspace_array, (5, 2))
print("Exercise 3: Reshaped Linspace Array:\n", reshaped_linspace)

Exercise 3: Reshaped Linspace Array:
 [[0.         0.11111111]
 [0.22222222 0.33333333]
 [0.44444444 0.55555556]
 [0.66666667 0.77777778]
 [0.88888889 1.        ]]


In [38]:
# Exercise 4: Extract all odd numbers from the random_array
odd_numbers = random_array[random_array % 2 == 0]
print("Exercise 4: Odd Numbers from Random Array:", odd_numbers)

Exercise 4: Odd Numbers from Random Array: [  4   8   4   2   8  -6 -10]


In [25]:
# Exercise 5: Create a 3x3 array with values from 0 to 8, then multiply it by 2
double_array = np.array(np.arange(9).reshape(3,3)) * 2
print("Exercise 5: Doubled Array:\n", double_array)

Exercise 5: Doubled Array:
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [26]:
# Exercise 6: Perform a matrix multiplication between random_array and double_array
matrix_multiplication_result = np.dot(random_array, double_array)
print("Exercise 6: Matrix Multiplication Result:\n", matrix_multiplication_result)

Exercise 6: Matrix Multiplication Result:
 [[11.32255783 14.27684071 17.2311236 ]
 [ 4.19374481  5.4178421   6.64193939]
 [ 8.30075527 10.82677352 13.35279176]]


In [27]:
# Exercise 7: Calculate the mean along the columns of matrix_multiplication_result
mean_along_columns = np.mean(matrix_multiplication_result, axis=0)
print("Exercise 7: Mean along Columns:\n", mean_along_columns)

Exercise 7: Mean along Columns:
 [ 7.9390193  10.17381878 12.40861825]


In [28]:
# Exercise 8: Create a boolean array where values greater than 0 in matrix_multiplication_result are True
boolean_array = (matrix_multiplication_result > 0)
print("Exercise 8: Boolean Array:\n", boolean_array)

Exercise 8: Boolean Array:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
# Exercise 9: Replace all negative values in random_array with 0
random_array[random_array < 0] = 0
print("Exercise 9: Replace Negative Values with 0:\n", random_array)

Exercise 9: Replace Negative Values with 0:
 [[0 4 8]
 [3 4 2]
 [8 0 0]]


In [42]:
# Exercise 10: Sum all values greater than 1 in reshaped_linspace
sum_greater_than_1 = np.sum(reshaped_linspace[reshaped_linspace > 1])
print("Exercise 10: Sum of Values > 1 in Reshaped Linspace:", sum_greater_than_1)

Exercise 10: Sum of Values > 1 in Reshaped Linspace: 0.0


In [56]:
# Exercise 11: Create a 4x4 array with values from a normal distribution (mean=0, standard deviation=1)
normal_distribution_array = np.random.normal(size=(4, 4),loc=0,scale=1)
print("Exercise 11: Normal Distribution Array:\n", normal_distribution_array)

Exercise 11: Normal Distribution Array:
 [[-0.90002718  0.42760385  1.34342568  0.79054853]
 [-1.41226048  2.16307402  0.892849    0.87396853]
 [ 1.52681554 -0.06303618 -0.89530595  0.62858963]
 [ 0.40297118 -0.3814465   1.97610303 -0.24701299]]


In [57]:
# Exercise 12: Calculate the standard deviation of each row in normal_distribution_array
std_deviation_per_row = np.std(normal_distribution_array, axis=1)
print("Exercise 12: Standard Deviation per Row:\n", std_deviation_per_row)

Exercise 12: Standard Deviation per Row:
 [0.82650857 1.28935571 0.89072961 0.93644578]


In [60]:
# Exercise 13: Create a 3x3 array with integer values, then flatten it
integer_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_array = integer_array.flatten()
ala_test = integer_array.reshape(-1,)
print("Exercise 13: Flattened Array:", flattened_array)
print("Exercise 13: ala test", ala_test)

Exercise 13: Flattened Array: [1 2 3 4 5 6 7 8 9]
Exercise 13: ala test [1 2 3 4 5 6 7 8 9]


In [65]:
# Exercise 14: Stack the integer_array vertically on top of itself
stacked_vertically = np.vstack((integer_array, integer_array))
print("Exercise 14: integer array:\n", integer_array)
print("Exercise 14: Stacked Vertically Array:\n", stacked_vertically)

Exercise 14: integer array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Exercise 14: Stacked Vertically Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
# Exercise 15: Split the stacked_vertically array into two separate arrays
split_arrays = np.vsplit(stacked_vertically, 2)
print("Exercise 15: Split Arrays:", split_arrays)

Exercise 15: Split Arrays: [array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]


In [72]:
# Exercise 16: Create an array with values from 0 to 2π with a step of π/4
theta_values = np.arange(0, 2*np.pi, np.pi/4)
print("Exercise 16: Theta Values Array:", theta_values)

Exercise 16: Theta Values Array: [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714]


In [73]:
# Exercise 17: Calculate the sine and cosine of theta_values
sine_values = np.sin(theta_values)
cosine_values = np.cos(theta_values)
print("Exercise 17: Sine Values Array:", sine_values)
print("             Cosine Values Array:", cosine_values)

Exercise 17: Sine Values Array: [ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01]
             Cosine Values Array: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01]


In [78]:
# Exercise 18: Calculate the element-wise natural logarithm of the std_deviation_per_row array
log_std_deviation = np.log(std_deviation_per_row)
print("Exercise 18: Logarithm of Standard Deviation:\n", log_std_deviation)

Exercise 18: Logarithm of Standard Deviation:
 [-0.19054499  0.25414265 -0.11571437 -0.06566365]


In [80]:
# Exercise 19: Calculate the dot product of the first row of integer_array and the last column of normal_distribution_array
dot_product_result = np.dot(integer_array[0, :], normal_distribution_array[:3, -1])
print("Exercise 19: Dot Product Result:", dot_product_result)

Exercise 19: Dot Product Result: 4.424254484492243


In [81]:
# Exercise 20: Create a boolean array where values in normal_distribution_array are greater than 1
boolean_array_greater_than_1 = (normal_distribution_array > 1)
print("Exercise 20: Boolean Array (Values > 1):\n", boolean_array_greater_than_1)

Exercise 20: Boolean Array (Values > 1):
 [[False False  True False]
 [False  True False False]
 [ True False False False]
 [False False  True False]]
