#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations

In [ ]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 3.9 MB/s eta 0:00:00a 0:00:01


In [4]:
import numpy as np

# creating array using numpy
arr_one = np.array([1,2,3,4,5])
print(arr_one)
print(arr_one.shape)
print(type(arr_one))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [5]:
arr_one.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
arr_two = np.array((1,2,3,4,5,6))

In [7]:
arr_two.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr_three= np.array([[1,2,3],[1,2,3]])
arr_three.shape

(2, 3)

In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [16]:
arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[1,2],[4,5]])
print(arr1)
print(arr2)
print(arr1 @ arr2)

[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[ 9 12]
 [24 33]]


In [17]:
print(arr_one)

[1 2 3 4 5]


In [18]:
print(np.sqrt(arr_one))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [20]:
arr1[1:,1:]

array([[5]])

In [25]:
arr1[0][1] = 1001

In [26]:
arr1

array([[ 100, 1001],
       [   4,    5]])